// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    ActivityCard: typeof import('./components/ActivityCard.vue')['default']
    CacheCard: typeof import('./components/OptionPanel/CacheCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    OptionPanel: typeof import('./components/OptionPanel/index.vue')['default']
    PasswordCard: typeof import('./components/OptionPanel/PasswordCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    Waves: typeof import('./components/Waves.vue')['default']
  }
}

export { }
